<?php

/**
 * PluginsbJobBoardApplicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbJobBoardApplicationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbJobBoardApplicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbJobBoardApplication');
    }
}