<?php

/**
 * PluginsbJobBoardJobToASearchDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbJobBoardJobToASearchDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbJobBoardJobToASearchDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbJobBoardJobToASearchDocument');
    }
}