<?php

/**
 * PluginsbJobBoardJobToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbJobBoardJobToCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbJobBoardJobToCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbJobBoardJobToCategory');
    }
}